config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'articles#index'
  resources :articles
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :move_to_index, except: [:index, :show]

  def index
    @articles = Article.includes(:user).page(params[:page]).per(5).order("created_at DESC")
  end

  def new
    @article = Article.new
  end

  def create
    Article.create(text: article_params[:text], user_id: current_user.id)
    redirect_to action: :index
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    article = Article.find(params[:id])
    if article.user_id == current_user.id
       article.update(article_params)
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy if @article.user_id == current_user.id
  end

    private
    def article_params
      params.require(:article).permit(:text, :id)
    end

    def move_to_index
      redirect_to action: :index unless user_signed_in?
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
     <div class="container">
       <div class="row">
 <div class="col s12 m8">
      <div class="card blue accent-1">
        <div class="card-content black-text">
          <%= article.text %>
        </div>
        <div class="card-action">
          <%  if user_signed_in? && current_user.id = article.user_id %>
          <%= link_to 'edit', "/articles/#{article.id}/edit", method: :get , class: "card-action-color"%>
          <%= link_to 'delete', "/articles/#{article.id}", method: :delete , class: "card-action-color"%>
          <% end %>
        </div>
      </div>
    </div>
        </div>
                </div>

app/views/articles/destroy.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        削除が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/articles/edit.html.erb
<div class="form-wrapper-new">
<h2>Edit Article</h2>
    <%= form_for @article do |f| %>
      <div class="form-item-new">
      <%= f.text_area :text, placeholder: '本文を入力してください', class: "form-item-new" %>
        </div>
     <div class="button-pannel-new">
    <%= f.submit class: "button-new" %>
  </div>
<% end %>
    </div>

app/views/articles/index.html.erb
<div class="row">
    <% @articles.each do |article| %>
            <%= render partial: "article", locals: { article:article }%>
            <% end %>
            <div class = "footer">
            <%= paginate(@articles) %>
            </div>
</div>

app/views/articles/new.html.erb
<div class="form-wrapper-new">
<h2>New Article</h2>
    <%= form_for @article do |f| %>
      <div class="form-item-new">
      <%= f.text_area :text, placeholder: '本文を入力してください', class: "form-item-new" %>
        </div>
     <div class="button-pannel-new">
    <%= f.submit class: "button-new" %>
  </div>
<% end %>
    </div>

app/views/articles/update.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        更新が完了しました。
      </h3>
          <div class = "backpage">
      <a class="btn" href="/">投稿一覧へ戻る</a>
          </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniBlog</title>
    <%= csrf_meta_tags %>
      <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
  <script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
   <nav class="pink accent-2">
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">MINI BLOG</a>
      <% if user_signed_in? %>
      <span><%= current_user.name %>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
        </li>
        <li>
          <%= link_to "New", new_article_path, method: :get %>
        </li>
      </ul>
      <% else %>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li>
          <%= link_to "Sign In", new_user_session_path, method: :get %>
        </li>
        <li>
          <%= link_to "Sign Up", new_user_registration_path, method: :get %>
        </li>
    </div>
    <% end %>
        <script type="text/javascript" src="./app.js"></script>
  </nav>
  </header>
    <%= yield %>
  </body>
</html>